import { Metadata } from 'next';
import Link from 'next/link';

import { ColorWheel } from '@/components/color-tools/color-wheel';
import { ToolPageShell, buildToolMetadata } from '@/components/color-tools/tool-page-shell';

const config = {
  title: 'Interactive Color Wheel — Pick Harmonies Online | Color Mapper',
  description:
    'Free interactive color wheel. Drag to pick a hue, see complementary, triadic, and analogous harmonies instantly — with HEX, RGB, and CMYK values.',
  url: '/color-wheel',
  h1: 'Interactive Color Wheel',
  intro:
    'Drag the marker to explore hues and saturations. Harmony markers update live, and every swatch carries HEX, RGB, and CMYK with print gamut warnings.',
  faq: [
    {
      question: 'How do I use a color wheel to pick colors?',
      answer:
        'Pick a base hue on the wheel, then apply a harmony rule: complementary (opposite), analogous (neighbors), or triadic (three evenly spaced hues). The markers show where each harmony color sits on the wheel.',
    },
    {
      question: 'What do the wheel markers mean?',
      answer:
        'The large marker is your base color. Smaller markers show the harmony colors generated by the selected scheme — their angle is the hue, their distance from center is the saturation.',
    },
    {
      question: 'Can I send wheel colors to other tools?',
      answer:
        'Yes. Open the current scheme in the palette generator to lock and refine swatches, or send all colors straight to the gradient generator.',
    },
    {
      question: 'Why do some swatches show a CMYK warning?',
      answer:
        'Saturated screen colors can sit outside the CMYK print gamut. The warning badge means the color will shift on press — check it in the HEX to CMYK converter before production.',
    },
  ],
};

export const metadata: Metadata = buildToolMetadata(config);

export default function ColorWheelPage() {
  return (
    <ToolPageShell
      config={{
        ...config,
        content: (
          <p>
            New to color relationships? Start with our{' '}
            <Link href="/blog/color-theory-101">color theory guide</Link>, then refine your picks
            in the <Link href="/palettes">palette generator</Link> or audit them with the{' '}
            <Link href="/contrast-checker">WCAG contrast checker</Link>.
          </p>
        ),
      }}>
      <ColorWheel />
    </ToolPageShell>
  );
}
