/**
 * Postbuild hook — sitemap is generated by app/sitemap.ts at build time.
 * Do not write empty sitemap stubs here (breaks SEO when MAINTENANCE_MODE is set).
 */
console.log('Postbuild complete (sitemap served from app/sitemap.ts).');
